### ISSUE TITLE
DeepInspect.optimize_mark() got an unexpected keyword argument 'verbose'

### ISSUE THREAD

**Issue by rahulxie** [ain-soph/trojanzoo#140]
"python backdoor_defense.py --color --verbose 1 --pretrained --validate_interval 1 --dataset cifar10 --model resnet18_comp --attack badnet --defense deep_inspect --mark_random_init --epochs 50 --lr
 0.01 --save  --tqdm" 
When I ran the command above to detect badnets with DeepInspect, I got the error: DeepInspect.optimize_mark() got an unexpected keyword argument 'verbose'. Please help me.

Traceback (most recent call last):
  File "/home/itl/Documents/xrh/backdoor/trojanzoo/examples/backdoor_defense.py", line 46, in <module>
    defense.detect(**trainer)
  File "/home/itl/Documents/xrh/backdoor/trojanzoo/examples/../trojanvision/defenses/abstract.py", line 345, in detect
    mark_list, loss_list, asr_list = self.get_mark_loss_list()
  File "/home/itl/Documents/xrh/backdoor/trojanzoo/examples/../trojanvision/defenses/abstract.py", line 386, in get_mark_loss_list
    mark, loss = self.optimize_mark(label, verbose=verbose, **kwargs)
TypeError: DeepInspect.optimize_mark() got an unexpected keyword argument 'verbose

**Comment by ain-soph** [comment]
Thanks for pointing it out. I'll check it later this week.

Btw, are you currently using the most up-to-date codes in GitHub rather than the release version?

**Comment by rahulxie** [comment]
> 

OK, I'll do it

**Comment by ain-soph** [comment]
Fixed by #142
