### ISSUE TITLE
TypeError: only integer tensors of a single element can be converted to an index

### ISSUE THREAD

**Issue by rahulxie** [ain-soph/trojanzoo#141]
"python backdoor_defense.py --color --verbose 1 --pretrained --validate_interval 1 --dataset cifar10 --model resnet18_comp --attack badnet --defense neuron_inspect --mark_random_init --epochs 50 --lr
0.01 --save --tqdm"
When I ran the command above to detect badnets with NeuronInspect, I got the error: "TypeError: only integer tensors of a single element can be converted to an index". Please help me.

Traceback (most recent call last):
  File "/home/itl/Documents/xrh/backdoor/trojanzoo/examples/backdoor_defense.py", line 46, in <module>
    defense.detect(**trainer)
  File "/home/itl/Documents/xrh/backdoor/trojanzoo/examples/../trojanvision/defenses/backdoor/model_inspection/neuron_inspect.py", line 48, in detect
    exp_features = self.get_explation_feature()
  File "/home/itl/Documents/xrh/backdoor/trojanzoo/examples/../trojanvision/defenses/backdoor/model_inspection/neuron_inspect.py", line 68, in get_explation_feature
    exp_features.append(self.cal_explanation_feature(backdoor_saliency_maps, benign_saliency_maps))
  File "/home/itl/Documents/xrh/backdoor/trojanzoo/examples/../trojanvision/defenses/backdoor/model_inspection/neuron_inspect.py", line 86, in cal_explanation_feature
    exp_feats = self.lambd_sp * sparse_feats + self.lambd_sm * smooth_feats + self.lambd_pe * persist_feats
TypeError: only integer tensors of a single element can be converted to an index

**Comment by ain-soph** [comment]
It's a bug of reading YAML config.

`1e-3` style will be read as string rather than float.

I fix it to be `1.e-3` so that it will be correctly read as float number.

**Comment by rahulxie** [comment]
> 



> It's a bug of reading YAML config.
> 
> `1e-3` style will be read as string rather than float.
> 
> I fix it to be `1.e-3` so that it will be correctly read as float number.

Right, I just find out. Haha.
