### ISSUE TITLE
Possible bug when loading GTSRB dataset

### ISSUE THREAD

**Issue by liu00222** [ain-soph/trojanzoo#41]
**Describe the bug**
When I tried to load the GTSRB dataset, I got some error messages. However, when I change the input argument from '-d gtsrb' to '-d mnist' or '-d cifar10', things went to work well. 

**To Reproduce**
Here is my test.py file: 

```
# -*- coding: utf-8 -*-

import trojanvision.datasets
import argparse


parser = argparse.ArgumentParser()
trojanvision.datasets.add_argument(parser)
args = parser.parse_args()

dataset = trojanvision.datasets.create(**args.__dict__)
print(type(dataset))
```

In the terminal, when I ran: 

```
python test.py -d mnist --download
python test.py -d cifar10 --download
```

The works were done successfully. The original data were downloaded and loaded into the script. However, when I tried to load GTSRB, I tried several different arguments: 

```
python test.py -d gtsrb --download
python test.py -d gtsrb --download --data_format zip
python test.py -d gtsrb --download --data_format folder
python test.py -d gtsrb --download --data_format numpy
```

Different errors were reported. I also tried to manually download the GTSRB.zip and placed it at ./datasets/data/data/image/ and re-ran the script, but things did not turn to work. For example. after manually downloading the dataset and unzipping it: 

```
python test.py -d gtsrb --data_dir ./data/data/ --data_format folder
```

I got:

```
Traceback (most recent call last):
  File "/home/yl764/datasets/test.py", line 11, in <module>
    dataset = trojanvision.datasets.create(**args.__dict__)
  File "/home/yl764/miniconda3/envs/datasets/lib/python3.9/site-packages/trojanvision/datasets/__init__.py", line 37, in create
    return trojanzoo.datasets.create(dataset_name=dataset_name, dataset=dataset,
  File "/home/yl764/miniconda3/envs/datasets/lib/python3.9/site-packages/trojanzoo/datasets.py", line 246, in create
    return DatasetType(folder_path=folder_path, **result)
  File "/home/yl764/miniconda3/envs/datasets/lib/python3.9/site-packages/trojanvision/datasets/gtsrb.py", line 17, in __init__
    super().__init__(loss_weights=loss_weights, **kwargs)
  File "/home/yl764/miniconda3/envs/datasets/lib/python3.9/site-packages/trojanvision/datasets/imagefolder.py", line 36, in __init__
    super().__init__(**kwargs)
  File "/home/yl764/miniconda3/envs/datasets/lib/python3.9/site-packages/trojanvision/datasets/imageset.py", line 26, in __init__
    super().__init__(default_model=default_model, **kwargs)
  File "/home/yl764/miniconda3/envs/datasets/lib/python3.9/site-packages/trojanzoo/datasets.py", line 89, in __init__
    self.loss_weights = self.get_loss_weights() if loss_weights else None
  File "/home/yl764/miniconda3/envs/datasets/lib/python3.9/site-packages/trojanzoo/datasets.py", line 192, in get_loss_weights
    _, targets = self.to_memory(dataset, label_only=True)
TypeError: to_memory() got multiple values for argument 'label_only'
```

**Expected behavior**
Load the dataset . 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by ain-soph** [comment]
Thanks for your bug report!
I admit there are potentially quite some bugs after so many times code re-organization. And we have no unit-test scripts yet.
I'll figure it out in one day, (hopefully).

**Comment by liu00222** [comment]
Many thanks for the response! I think my problem is gone now.
