### ISSUE TITLE
Error in `get_filename`

### ISSUE THREAD

**Issue by hkunzhe** [ain-soph/trojanzoo#43]
**Describe the bug**
Traceback (most recent call last):
  File "/home/hkz/trojanzoo/backdoor_attack.py", line 38, in <module>
    attack.attack(**trainer)
  File "/home/hkz/trojanzoo/trojanvision/attacks/backdoor/badnet.py", line 67, in attack
    self.model._train(epoch, save=save,
  File "/home/hkz/trojanzoo/trojanzoo/models.py", line 429, in _train
    save_fn(file_path=file_path, folder_path=folder_path, suffix=suffix, verbose=verbose)
  File "/home/hkz/trojanzoo/trojanvision/attacks/backdoor/badnet.py", line 107, in save
    filename = self.get_filename(**kwargs)
  File "/home/hkz/trojanzoo/trojanvision/attacks/backdoor/badnet.py", line 94, in get_filename
    mark_name, mark_ext = os.path.splitext(mark_filename)
  File "/home/hkz/anaconda3/envs/trojanzoo/lib/python3.9/posixpath.py", line 118, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not tuple

**To Reproduce**
1. git clone the current repo and download the cifar10 dataset
2. mv backdoor_attack.py from `example` dir to the repo root
3. run the quick start example
`python backdoor_attack.py --verbose 1 --validate_interval 1 --amp --dataset cifar10 --model resnetcomp18 --attack badnet --random_init --epoch 50 --lr 0.01 --save` without `--pretrain`

**Screenshots**
![image](https://user-images.githubusercontent.com/30763967/103761849-4891ff00-5052-11eb-8333-4f087e2d8b82.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Version git commit id 7478061

**Comment by ain-soph** [comment]
A stupid error when I use `filename:str=os.path.split(filepath)` without `[-1]`
