### ISSUE TITLE
Error in the reflection backdoor attack

### ISSUE THREAD

**Issue by hkunzhe** [ain-soph/trojanzoo#50]
**Describe the bug**
Traceback (most recent call last):
  File "/home/hkz/trojanzoo/backdoor_attack.py", line 38, in <module>
    attack.attack(**trainer)
  File "/home/hkz/trojanzoo/trojanvision/attacks/backdoor/reflection_backdoor.py", line 65, in attack
    self.model.load()
  File "/home/hkz/trojanzoo/trojanzoo/models.py", line 280, in load
    raise e
  File "/home/hkz/trojanzoo/trojanzoo/models.py", line 277, in load
    _dict: OrderedDict[str, torch.Tensor] = torch.load(file_path, map_location=map_location, **kwargs)
  File "/home/hkz/anaconda3/envs/trojanzoo/lib/python3.9/site-packages/torch/serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/hkz/anaconda3/envs/trojanzoo/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/hkz/anaconda3/envs/trojanzoo/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'data/model/image/cifar10/resnetcomp18.pth'
**To Reproduce**
`python backdoor_attack.py --verbose 1 --color --validate_interval 1 --dataset cifar10 --model resnetcomp18 --attack reflection_backdoor --random_init --epoch 50 --lr 0.01 --save --train_mode dataset`

**Screenshots**
![image](https://user-images.githubusercontent.com/30763967/103857210-ff44bc80-50f0-11eb-8f62-484d384a5d56.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - version: https://github.com/ain-soph/trojanzoo/commit/aeb448245a40ed14f52209d93de78b0a062fe1f2

**Comment by ain-soph** [comment]
Ah. I see, in my testing case, I always use a pretrained model for attack.  
Reflection attack requires to set model back to initial status. So I call model.load(). But when you don’t use a pretrained model, things gonna be wrong. We should fix it to be initialize as random numbers when —pretrain is not passed.

Btw, I test most attacks from pretrained models and only study few cases of attacking from scratch. (See trojanzoo paper)

**Comment by ain-soph** [comment]
I’ll fix it tmr morning.

**Comment by hkunzhe** [comment]
Ok, I see. I have tried to reproduce the results of the reflection attack according to the authors' origin code and poisoned dataset. However, I found it quite tricky to get a similar result with the paper. Hope to get a satisfactory result from your repo:)
