### ISSUE TITLE
Error when run the reflection backdoor attack

### ISSUE THREAD

**Issue by Urdarbrunner** [ain-soph/trojanzoo#54]
**Describe the bug**
Traceback (most recent call last):
  File "/home/workspace/backdoor_attack.py", line 37, in <module>
    attack.attack(**trainer)
  File "/home/workspace/trojanvision/attacks/backdoor/reflection_backdoor.py", line 46, in attack
    loader = self.dataset.get_dataloader(mode='train', batch_size=self.candidate_num, classes=[self.target_class],
  File "/home/workspace/trojanvision/datasets/imageset.py", line 43, in get_dataloader
    dataset = self.get_dataset(mode, **kwargs)
  File "/home/workspace/trojanzoo/datasets/dataset.py", line 148, in get_dataset
    dataset = self.get_class_set(dataset=dataset, classes=classes)
  File "/home/workspace/trojanzoo/datasets/dataset.py", line 158, in get_class_set
    _, targets = cls.to_memory(dataset=dataset, label_only=True)
  File "/home/workspace/trojanvision/datasets/imageset.py", line 77, in to_memory
    data, targets = super().to_memory(dataset=dataset, label_only=label_only)
TypeError: super(type, obj): obj must be an instance or subtype of type

**To Reproduce**
`python backdoor_attack.py --verbose 1 --color --validate_interval 1 --dataset cifar10 --model resnet18 --attack reflection_backdoor --random_init --epoch 50 --lr 0.01 --save --train_mode dataset` 

**Screenshots**
![图片](https://user-images.githubusercontent.com/62340034/114149723-cca79b80-994d-11eb-9f58-664f3ccbe526.png)

**Desktop**
Ubuntu 5.4.0-6ubuntu1~16.04.12

**Additional context**
The same problem also occur when run `clean_label` attack

**Comment by ain-soph** [comment]
`Reflection` and `Clean Label` seem to be implemented incorrectly. I'm working on this these days. (`Reflection` is using a wrong algorithm, and `Clean Label` not working yet.)  
Sorry for missing your issue. And this bug is already fixed recently.

**Comment by ain-soph** [comment]
They are fixed now.
