### ISSUE TITLE
Installation Error: No module named "torch"

### ISSUE THREAD

**Issue by AlgebraLoveme** [ain-soph/trojanzoo#55]
**Problem Description**

I downloaded the package and used pip to install. I am sure my environment has torch installed but I got an error saying "no module named torch".

**Output from "conda list | grep torch"**
```
pytorch-lightning         1.2.6                    pypi_0    pypi
torch                     1.7.1+cu110              pypi_0    pypi
torchaudio                0.7.2                    pypi_0    pypi
torchfile                 0.1.0                    pypi_0    pypi
torchmetrics              0.2.0                    pypi_0    pypi
torchsummary              1.5.1                    pypi_0    pypi
torchvision               0.8.2+cu110              pypi_0    pypi
```

**Output from "pip3 install trojanzoo-master.zip"**

```
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing ./trojanzoo-master.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/zjunesa/anaconda2/envs/myh/bin/python /home/zjunesa/anaconda2/envs/myh/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmph1f7a19_
       cwd: /tmp/pip-req-build-c6kjz7z2
  Complete output (64 lines):
  Traceback (most recent call last):
    File "/tmp/pip-build-env-qrekwfu_/overlay/lib/python3.7/site-packages/setuptools/config.py", line 35, in __getattr__
      for statement in self.module.body
  StopIteration
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/tmp/pip-build-env-qrekwfu_/overlay/lib/python3.7/site-packages/setuptools/config.py", line 387, in _parse_attr
      return getattr(StaticModule(module_name), attr_name)
    File "/tmp/pip-build-env-qrekwfu_/overlay/lib/python3.7/site-packages/setuptools/config.py", line 43, in __getattr__
      ) from e
  AttributeError: trojanzoo has no attribute __version__
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call `last):`
    File "/home/zjunesa/anaconda2/envs/myh/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/zjunesa/anaconda2/envs/myh/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/zjunesa/anaconda2/envs/myh/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-qrekwfu_/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 155, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-qrekwfu_/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-qrekwfu_/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 4, in <module>
      setuptools.setup()
    File "/tmp/pip-build-env-qrekwfu_/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/zjunesa/anaconda2/envs/myh/lib/python3.7/distutils/core.py", line 121, in setup
      dist.parse_config_files()
    File "/tmp/pip-build-env-qrekwfu_/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 716, in parse_config_files
      ignore_option_errors=ignore_option_errors)
    File "/tmp/pip-build-env-qrekwfu_/overlay/lib/python3.7/site-packages/setuptools/config.py", line 157, in parse_configuration
      meta.parse()
    File "/tmp/pip-build-env-qrekwfu_/overlay/lib/python3.7/site-packages/setuptools/config.py", line 463, in parse
      section_parser_method(section_options)
    File "/tmp/pip-build-env-qrekwfu_/overlay/lib/python3.7/site-packages/setuptools/config.py", line 436, in parse_section
      self[name] = value
    File "/tmp/pip-build-env-qrekwfu_/overlay/lib/python3.7/site-packages/setuptools/config.py", line 220, in __setitem__
      value = parser(value)
    File "/tmp/pip-build-env-qrekwfu_/overlay/lib/python3.7/site-packages/setuptools/config.py", line 552, in _parse_version
      version = self._parse_attr(value, self.package_dir)
    File "/tmp/pip-build-env-qrekwfu_/overlay/lib/python3.7/site-packages/setuptools/config.py", line 390, in _parse_attr
      module = importlib.import_module(module_name)
    File "/home/zjunesa/anaconda2/envs/myh/lib/python3.7/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 728, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/tmp/pip-req-build-c6kjz7z2/trojanzoo/__init__.py", line 5, in <module>
      from trojanzoo import environ as environ
    File "/tmp/pip-req-build-c6kjz7z2/trojanzoo/environ.py", line 3, in <module>
      from trojanzoo.utils.environ import *
    File "/tmp/pip-req-build-c6kjz7z2/trojanzoo/utils/__init__.py", line 3, in <module>
      import torch.cuda
  ModuleNotFoundError: No module named 'torch'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/zjunesa/anaconda2/envs/myh/bin/python /home/zjunesa/anaconda2/envs/myh/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmph1f7a19_ Check the logs for full command output.
```

**System**
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Output from "pip3 install trojanzoo"**
```
Looking in indexes: https://pypi.org/simple/
WARNING: Keyring is skipped due to an exception: Failed to create the collection: Prompt dismissed..
ERROR: Could not find a version that satisfies the requirement trojanzoo
ERROR: No matching distribution found for trojanzoo
```

**Comment by ain-soph** [comment]
Thanks for using TrojanZoo.  
Haven't used pypi for a long time. Let me check about that. I think it should be okay since the auto CI works fine.  
Could you test if you can use `python setup.py` to install normally?

**Comment by ain-soph** [comment]
Btw, your pytorch version is too low. I've been using quite a lot new features in pytorch 1.8.1.  
And Trojanzoo also requires `python>=3.9.2`

**Comment by AlgebraLoveme** [comment]
**Output from "python setup.py develop"**

```
Traceback (most recent call last):
  File "/home/zjunesa/anaconda2/envs/myh/lib/python3.7/site-packages/setuptools/config.py", line 35, in __getattr__
    for statement in self.module.body
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zjunesa/anaconda2/envs/myh/lib/python3.7/site-packages/setuptools/config.py", line 387, in _parse_attr
    return getattr(StaticModule(module_name), attr_name)
  File "/home/zjunesa/anaconda2/envs/myh/lib/python3.7/site-packages/setuptools/config.py", line 43, in __getattr__
    ) from e
AttributeError: trojanzoo has no attribute __version__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    setuptools.setup()
  File "/home/zjunesa/anaconda2/envs/myh/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/zjunesa/anaconda2/envs/myh/lib/python3.7/distutils/core.py", line 121, in setup
    dist.parse_config_files()
  File "/home/zjunesa/anaconda2/envs/myh/lib/python3.7/site-packages/setuptools/dist.py", line 668, in parse_config_files
    ignore_option_errors=ignore_option_errors)
  File "/home/zjunesa/anaconda2/envs/myh/lib/python3.7/site-packages/setuptools/config.py", line 157, in parse_configuration
    meta.parse()
  File "/home/zjunesa/anaconda2/envs/myh/lib/python3.7/site-packages/setuptools/config.py", line 463, in parse
    section_parser_method(section_options)
  File "/home/zjunesa/anaconda2/envs/myh/lib/python3.7/site-packages/setuptools/config.py", line 436, in parse_section
    self[name] = value
  File "/home/zjunesa/anaconda2/envs/myh/lib/python3.7/site-packages/setuptools/config.py", line 220, in __setitem__
    value = parser(value)
  File "/home/zjunesa/anaconda2/envs/myh/lib/python3.7/site-packages/setuptools/config.py", line 552, in _parse_version
    version = self._parse_attr(value, self.package_dir)
  File "/home/zjunesa/anaconda2/envs/myh/lib/python3.7/site-packages/setuptools/config.py", line 390, in _parse_attr
    module = importlib.import_module(module_name)
  File "/home/zjunesa/anaconda2/envs/myh/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/myh/single_ensemble_neuron/trojanzoo-master/trojanzoo/__init__.py", line 5, in <module>
    from trojanzoo import environ as environ
  File "/home/myh/single_ensemble_neuron/trojanzoo-master/trojanzoo/environ.py", line 3, in <module>
    from trojanzoo.utils.environ import *
  File "/home/myh/single_ensemble_neuron/trojanzoo-master/trojanzoo/utils/__init__.py", line 5, in <module>
    from .tensor import *
  File "/home/myh/single_ensemble_neuron/trojanzoo-master/trojanzoo/utils/tensor.py", line 3, in <module>
    from .environ import env
  File "/home/myh/single_ensemble_neuron/trojanzoo-master/trojanzoo/utils/environ.py", line 4, in <module>
    from .param import Param
  File "/home/myh/single_ensemble_neuron/trojanzoo-master/trojanzoo/utils/param.py", line 14, in <module>
    class Module(MutableMapping[_KT, _VT], Generic[_KT, _VT]):
  File "/home/myh/single_ensemble_neuron/trojanzoo-master/trojanzoo/utils/param.py", line 17, in Module
    def __init__(self, *args: list[Mapping[_KT, _VT]], **kwargs):
TypeError: 'type' object is not subscriptable
```

**Comment by ain-soph** [comment]
```
TypeError: 'type' object is not subscriptable
```  
This information shows your python version is lower than 3.9. You shall update it to >=3.9.2

**Comment by ain-soph** [comment]
I've tested on python:latest docker with running `pip install trojanzoo` and it works fine. The basic datasets and models are working well as well, so I think it should be a problem of your local environment.  
If you like to use docker, you can just use my trojanzoo docker at https://hub.docker.com/r/local0state/trojanzoo .  
Or my environment setting at https://hub.docker.com/r/local0state/base

**Comment by AlgebraLoveme** [comment]
Thanks! Update to py3.9.0 and pytorch1.8.0 solved my problem.

**Comment by ain-soph** [comment]
> Thanks! Update to py3.9.0 and pytorch1.8.0 solved my problem.

Great to hear it. But have to tell you `python 3.9.2` fixes a type annotation bug of `collections.abc.Callable`. You have to make sure your python version >= 3.9.2, otherwise it'll throw exceptions.
